// Why: omp announces each task-tool sub-agent on its event bus (`task:subagent:lifecycle`), which
// the lead binding turns into the same `subagents` list Claude and Codex panes carry. The roster
// is module-level so a lead reload keeps children that are still running.
export function getPiAgentStatusSubagentRosterSourceLines(): string[] {
  return [
    '// Mirrors AGENT_STATUS_MAX_SUBAGENTS and the 64-char id cap in agent-status-types.',
    'const OMP_SUBAGENT_MAX = 32',
    'const OMP_SUBAGENT_ID_MAX_LENGTH = 64',
    'const ompSubagentRoster: Map<string, { agentType?: string; description?: string; startedAt: number }> = new Map()',
    '',
    '// Why: nested omp ids ("Parent.Child") can outgrow the cap; keep them unique instead of dropping them.',
    'function clampOmpSubagentId(id: string): string {',
    '  if (id.length <= OMP_SUBAGENT_ID_MAX_LENGTH) return id',
    '  let hash = 5381',
    '  for (let i = 0; i < id.length; i += 1) hash = ((hash << 5) + hash + id.charCodeAt(i)) >>> 0',
    "  const suffix = '~' + hash.toString(16)",
    '  return id.slice(0, OMP_SUBAGENT_ID_MAX_LENGTH - suffix.length) + suffix',
    '}',
    '',
    '/** Returns true when the roster changed. */',
    'function applyOmpSubagentLifecycle(frame: unknown): boolean {',
    "  if (!frame || typeof frame !== 'object') return false",
    '  const { id, agent, description, status } = frame as { id?: unknown; agent?: unknown; description?: unknown; status?: unknown }',
    "  if (typeof id !== 'string' || !id.trim()) return false",
    '  const key = clampOmpSubagentId(id.trim())',
    "  if (status === 'started') {",
    '    const existing = ompSubagentRoster.get(key)',
    '    if (!existing && ompSubagentRoster.size >= OMP_SUBAGENT_MAX) return false',
    '    ompSubagentRoster.set(key, {',
    "      agentType: typeof agent === 'string' && agent ? agent : existing?.agentType,",
    "      description: typeof description === 'string' && description ? description : existing?.description ?? id,",
    '      startedAt: existing?.startedAt ?? Date.now(),',
    '    })',
    '    return true',
    '  }',
    "  if (status === 'completed' || status === 'failed' || status === 'aborted') {",
    '    return ompSubagentRoster.delete(key)',
    '  }',
    '  return false',
    '}',
    '',
    '// Why: a missed end frame must not pin a row forever; omp 18.2.1+ lists the jobs still running.',
    'function reconcileOmpSubagents(ctx: unknown): void {',
    '  if (ompSubagentRoster.size === 0) return',
    '  const getSnapshot = (ctx as { getAsyncJobSnapshot?: () => unknown } | null)?.getAsyncJobSnapshot',
    "  if (typeof getSnapshot !== 'function') return",
    '  let running: unknown',
    '  try {',
    '    running = (getSnapshot.call(ctx) as { running?: unknown } | null)?.running',
    '  } catch {',
    '    return',
    '  }',
    '  if (!Array.isArray(running)) return',
    '  const live = new Set<string>()',
    '  for (const job of running) {',
    '    const { id, agentId } = (job ?? {}) as { id?: unknown; agentId?: unknown }',
    "    if (typeof id === 'string') live.add(clampOmpSubagentId(id))",
    "    if (typeof agentId === 'string') live.add(clampOmpSubagentId(agentId))",
    '  }',
    '  for (const key of [...ompSubagentRoster.keys()]) {',
    '    if (!live.has(key)) ompSubagentRoster.delete(key)',
    '  }',
    '}',
    '',
    '// Why: read when a post drains, so the latest-only queue can never drop a start or a stop.',
    '// Always an array: [] tells Muster this extension owns the roster.',
    'function snapshotOmpSubagents(): Array<Record<string, unknown>> {',
    '  return [...ompSubagentRoster].map(([id, tracked]) => ({',
    '    id,',
    '    ...(tracked.agentType ? { agentType: tracked.agentType } : {}),',
    '    ...(tracked.description ? { description: tracked.description } : {}),',
    "    state: 'working',",
    '    startedAt: tracked.startedAt,',
    '  }))',
    '}',
    ''
  ]
}
