// Installs and configures the extensions Muster ships itself.
//
// A bundled extension is copied out of resources into <userData>/extensions/<slug> before it is
// loaded, because Electron only loads unpacked directories and the packaged copy lives inside a
// read-only Resources tree. Configuration is written as a generated `config.js` that runs first
// in the extension's own content_scripts entry: Electron's chrome.storage support is partial and
// an extension popup is unreachable to an agent, so Muster owns the settings instead.

import { copyFileSync, existsSync, mkdirSync, readdirSync, rmSync, statSync } from 'node:fs'
import path from 'node:path'
import * as electron from 'electron'
import { getCanonicalUserDataPath } from '../persistence'
import { writeSecureFile } from '../../shared/secure-file'
import type {
  BundledExtensionId,
  WordPressLoginAutofillConfig
} from '../../shared/browser-extension-types'

type BundledExtensionDefinition = {
  id: BundledExtensionId
  /** Directory name under resources/browser-extensions and <userData>/extensions. */
  slug: string
  name: string
  description: string
}

export const BUNDLED_EXTENSIONS: readonly BundledExtensionDefinition[] = [
  {
    id: 'wordpress-login-autofill',
    slug: 'wordpress-login-autofill',
    name: 'WordPress Login Autofill',
    description:
      'Fills wp-login.php with credentials you configure here. Skips a failed login and a deliberate logout so it never loops.'
  }
]

export function getBundledExtensionDefinition(id: string): BundledExtensionDefinition | null {
  return BUNDLED_EXTENSIONS.find((entry) => entry.id === id) ?? null
}

/** Where the shipped copy lives: extraResources in a packaged app, the repo in dev. */
export function getBundledExtensionSourceDir(slug: string): string | null {
  const candidates = electron.app.isPackaged
    ? [path.join(process.resourcesPath, 'browser-extensions', slug)]
    : [
        path.join(electron.app.getAppPath(), 'resources', 'browser-extensions', slug),
        path.join(process.cwd(), 'resources', 'browser-extensions', slug)
      ]
  return candidates.find((candidate) => existsSync(candidate)) ?? null
}

export function getInstalledExtensionsDir(): string {
  return path.join(getCanonicalUserDataPath(), 'extensions')
}

export function getInstalledBundledExtensionDir(slug: string): string {
  return path.join(getInstalledExtensionsDir(), slug)
}

export function isBundledExtensionInstalled(slug: string): boolean {
  return existsSync(path.join(getInstalledBundledExtensionDir(slug), 'manifest.json'))
}

function copyDirectoryContents(sourceDir: string, targetDir: string): void {
  mkdirSync(targetDir, { recursive: true })
  for (const entry of readdirSync(sourceDir)) {
    const source = path.join(sourceDir, entry)
    const target = path.join(targetDir, entry)
    if (statSync(source).isDirectory()) {
      copyDirectoryContents(source, target)
      continue
    }
    copyFileSync(source, target)
  }
}

export type InstallBundledExtensionResult =
  | { ok: true; path: string }
  | { ok: false; message: string }

export function installBundledExtension(id: string): InstallBundledExtensionResult {
  const definition = getBundledExtensionDefinition(id)
  if (!definition) {
    return { ok: false, message: `Unknown bundled extension: ${id}` }
  }
  const sourceDir = getBundledExtensionSourceDir(definition.slug)
  if (!sourceDir) {
    return { ok: false, message: 'Bundled extension files are missing from this build.' }
  }
  const targetDir = getInstalledBundledExtensionDir(definition.slug)
  try {
    // Why: replace rather than merge so a Muster upgrade cannot leave stale extension files
    // behind, while the generated config is rewritten immediately below.
    rmSync(targetDir, { recursive: true, force: true })
    copyDirectoryContents(sourceDir, targetDir)
    return { ok: true, path: targetDir }
  } catch (error) {
    return { ok: false, message: error instanceof Error ? error.message : String(error) }
  }
}

export function uninstallBundledExtension(id: string): boolean {
  const definition = getBundledExtensionDefinition(id)
  if (!definition) {
    return false
  }
  try {
    rmSync(getInstalledBundledExtensionDir(definition.slug), { recursive: true, force: true })
    return true
  } catch {
    return false
  }
}

function serializeConfig(config: WordPressLoginAutofillConfig): string {
  // JSON.stringify keeps a password containing quotes or newlines from breaking out of the literal.
  const payload = JSON.stringify({
    username: config.username,
    password: config.password,
    autoLogin: config.autoLogin === true
  })
  return `// Generated by Muster. Edit these credentials in Settings, not here.\nglobalThis.__MUSTER_WP_LOGIN__ = ${payload}\n`
}

/**
 * Writes the credentials the content script reads. The file lands inside the installed extension
 * with owner-only permissions — an extension's own config is readable by that extension either
 * way, so this matches what chrome.storage would expose while keeping other users out.
 */
export function writeWordPressLoginConfig(config: WordPressLoginAutofillConfig): boolean {
  const definition = getBundledExtensionDefinition('wordpress-login-autofill')
  if (!definition || !isBundledExtensionInstalled(definition.slug)) {
    return false
  }
  const configPath = path.join(getInstalledBundledExtensionDir(definition.slug), 'config.js')
  try {
    writeSecureFile(configPath, serializeConfig(config))
    return true
  } catch {
    return false
  }
}
